#version 430
layout(local_size_x = 32, local_size_y = 32) in;

uniform ivec2 size;
layout(binding = 0) uniform isampler2D tex; // global triangle ID or -1
layout(std430, binding = 0) buffer Mark {
    int mark[];
};

void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (p.x < size.x && p.y < size.y) {
        int id = texelFetch(tex, p, 0).x;
        if (id >= 0) mark[id] = 1;
    }
}